DROP DATABASE IF EXISTS worstBuyReviews;

CREATE DATABASE worstBuyReviews;

USE worstBuyReviews;

CREATE TABLE products (
  id int AUTO_INCREMENT PRIMARY KEY,
  sku int NOT NULL,
  brand VARCHAR(255),
  product_title VARCHAR(255),
  product_desc VARCHAR(255),
  sale_price DECIMAL(10, 2) NOT NULL,
  msrp DECIMAL(10, 2) NOT NULL,
  quantity int NOT NULL,
  star_rating int,
  catagory VARCHAR(255) NOT NULL
);

CREATE TABLE reviews (
  id int AUTO_INCREMENT PRIMARY KEY,
  product_sku int NOT NULL,
  username VARCHAR(20),
  review_body VARCHAR(255),
  star_rating int,
  recommended VARCHAR(255),
  review_title VARCHAR(255),
  verified VARCHAR(255),
  date VARCHAR(255) NOT NULL
);

INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235601, 'Samsing', 'Industrial Size washing machine', 'A washing machine with the quality of a laundrimat machine, able to wash an entire sweat shops uniforms in one load', 1499.99, 1500.00, 8, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235602, 'LH', 'Bottom control dishwasher', 'A dishwasher where you would lay on the floor to operate controls. Allows easy loading of dishwasher', 1999.99, 699.99, 7, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235603, 'Whurlpool', 'Left of range microwave', 'A microwave that SPECIFICALLY gets placed to the LEFT of your range.', 1499.99, 799.99, 12, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235604, 'Maytog', 'No door refigerator', 'A easy to not access refigerator for those trying to lose weight', 2999.99, 3499.99, 10, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235605, 'KitchenHinder', 'Low performance blender', 'A blender that may be worse than just dicing with a knife', 169.99, 199.99, 1, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235606, 'Dieson', 'Super sonic hair wetter', 'Makes wetting your hair outside of the shower quick and easy with no hoses attached!', 79.99, 119.99, 8, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235607, 'Keurigged', 'K classic', 'Our classic K coffee maker will sometimes brew your coffee when asked. Good luck setting it up', 39.99, 49.99, 22, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235608, 'jRobot', 'Claymore Roomba', 'The classic take on the Roomba, but with a claymore anit-personel mine strapped to the top. Will trigger when anything gets in the way, use with care!', 1049.99, 1299.99, 3, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235609, 'Posche', 'Convertible range hood', 'Actually blows air onto your range top.', 999.99, 1499.99, 19, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235610, 'Volcanicair', 'Non-stainless steel refrigerator', 'Nice finish refigerator that will last you about a week in humid climates. (finish may rust over time)', 1499.99, 1799.99, 6, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235611, 'BE appliances', 'Free standing electric range', "The perfect addition to your kitchen if you aren't good at cooking so you can blame it on the fact that it's electric and doesn't heat correctly.", 899.99, 999.99, 5, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235612, 'Atlantic kitchen', 'Dracor refigerator', 'You want to flex in all of your friends and family? Pick up this sweet refigerator that has hologram numbers to tell you the exact temperature.', 35999.99, 19999.99, 45, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235613, 'Samsing', 'Family Hub 94 cu. in. refrigerator', 'For those families that LOVE to eat and love to spend 800 bucks a week on groceries then eat out anyway.', 799.99, 999.99, 1, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235614, 'Samsing', 'Under the range mirowave', 'This mircowave conveniently sits underneath your range so you can cook while you cook dawg.', 78.99, 84.99, 8, 5, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235615, 'Samsing', 'POWERbot robot vacuum cleaner', "This robot vacuum cleaner is way less cool than the claymore Roomba, but probably won't blow up upon contact with walls.", 389.99, 399.99, 16, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235616, 'Samsing', 'High Tech dryer', 'The highest of high tech clothes dryer for any amount of clothes you could possibly load.', 44.99, 68.99, 3, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235617, 'Dieson', 'Ball Animal vacuum cleaner', 'Picks all those pesky animals right off of the floor of your home, works up to 25lb body weight animals', 249.99, 299.99, 5, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235618, 'Dieson', 'Max cool fan', "Kind of just blows stale air for those of you that don't have central air in the year 2020", 34.99, 49.99, 89, 1, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235619, 'Dieson', 'V7 cordless hand vac', 'Cordless hand held vacuum that has about 2 minutes of run time with a 4 hour recharge!', 159.99, 189.99, 6, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235620, 'Keurigged', 'Latte maker', 'Makes a mediocre latte with mostly milk and room temperature, perfect for those that are not really big into coffee, but huge into milk!', 129.99, 189.99, 18, 1, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235621, 'Keurigged', 'Single serve and carafe coffee maker', 'Makes about a third of a cup of coffee per K cup! ', 12.99, 19.99, 56, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235622, 'Keurigged', 'K-Elite coffee maker', 'Makes about a half a cup of coffee and looks pretty cool! Guaranteed at least one usage', 89.99, 99.99, 5, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235623, 'Volcanicair', "Short tub built in dishwasher", "Fits about one plate in there! Who doesn't want to wash one dish at a time?", 999.99, 1199.99, 8, 1, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235624, 'Volcanicair', 'Gas cook-top', 'Gas cooktop that uses portable propane tanks to fuel it. Has about 15 seconds of runtime per propane tank!', 1199.99, 1499.99, 14, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235625, 'Volcanicair', 'Self-dirtying oven', 'Everything you could ever want in an oven. Seems to make itself dirty even without use somehow.', 799.99, 1199.99, 18, 3, 'Appliances');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510121,'Nintendo','Super Smashed Bros','Bros get quarantined at home',39.99,59.99,5,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510122,'Nintendo','Montris','Drop one block at at time to clear lines',39.99,59.99,8,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510123,'Nintendo','Snac-Man','Race to buy all the snacks and toilet paper from HEB',39.99,59.99,3,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510124,'Nintendo','Dankey Kang','Become the first caveman to discover fire to warm up his uncomfortably dank cave',39.99,59.99,5,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510125,'Nintendo','Gagala','Help lady gaga fight off oncoming paparazzi',39.99,59.99,12,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510126,'Nintendo','007: Pink in Eye','Get your first pair of trial contact lenses and go about a routine day',39.99,59.99,8,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510127,'Nintendo','Average Mario','Get through technical school to become a plumbler',39.99,59.99,3,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510128,'Nintendo','Duck Hunt','Go to different locations on the hunt for ducks',39.99,59.99,1,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510129,'Nintendo','Kirby','You are a pink ball that can absorb all sorts of items and become variations of what you absorbed',39.99,59.99,5,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510130,'Activision','Call of Jury Duty: Modern Inconvenience','Sit in the court house all day with vary levels of disagreeing juries',29.99,59.99,3,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510131,'Activision','To Catch a Pokemon','Chris Ketchum shows you the way the catch evil Pokemon poachers',29.99,59.99,14,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510132,'Activision','To Kill a Mockingbird','First person shooter',29.99,59.99,9,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510133,'Activision','Overclock','Adjust difference settings to try to lower your pc temp',29.99,59.99,6,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510134,'Electronic Arts','Sonic The Restaurant','Rollerskates and tips, what''s the deal?',49.99,59.99,11,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510135,'Electronic Arts','John Sick 2','Dealing with the second wave of the coronavirus',49.99,59.99,2,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510136,'Sony','Rhymecraft','Starting from nothing from the streets of Compton, build your own rap career by hand',49.99,59.99,23,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510137,'Sony','The Amazing Raccoon Man 2','Run around the community checking to see if people are properly recycling',49.99,59.99,53,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510138,'Ubisoft','The Elder Scrolls XVI','Teach your grandmother for the 16th time how to Google something',49.99,59.99,16,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510139,'PUBG Corp','PlayerVeryKnown Battlegrounds','Jail simulator',49.99,59.99,46,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510140,'Capcom','Resident Evil','Quarantine simulator of 2020 coronavirus pandemic',49.99,59.99,86,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510141,'Capcom','Rock Paper Scissors with a twist','rock paper scissors with a twist',49.99,59.99,54,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510142,'Capcom','Street Fighter: 6th Street','You are a bum named Roger and have to fight your way to survive on 6th street',39.99,59.99,2,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510143,'Midway','Mortal Kombat','VR fight a family member of your choice',39.99,59.99,4,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510144,'Sega','Krogger','Try to cross to checkout through hustling and bustling rows of shoppers',39.99,59.99,7,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (510145,'King','Candy Crush','Crush all sorts of candy to clear them all',39.99,59.99,2,1,'media');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125610,'FakeU','Shooting lessons','With a trained bestbuy photogopher you will see a big difference in clarity. You will learn what to shoot and how to frame it.',99.99,99.99,10,5,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125611,'Trash Cannon','PowerShot','This elegant camera will make sure that you can take the best photos. You can use our new 2x zoom feature',199.99,299.99,12,4.5,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125612,'Trash Cannon','SD Card','This is a very fast 250MB storage unit for all of the photos you will ever take.',49.99,59.99,8,3,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125613,'Trash Cannon','Rugged Wrist Strap','This rest wrap will make sure youre new camera never falls off your wrist. You will lose blood cirulation before thats possbile.',78.50,79.99,5,4.6,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125614,'Trash Cannon','Replacement Battery','This battery will allow you to take twice as many photos.',89.99,99.99,11,3,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125615,'Trash Cannon','Camera Tri Pod','A updated tri pod of our previous version, for increased adjustability, increased durability.',139.99,150.00,3,4.8,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125616,'Trash Cannon','Studio Lighting','This light will illuminate any subject no matter the size. This bad boy will need to be powered by a 220V plug. But your camera loves light, don''t you want what is best for your camera?',399.99,499.99,1,2.1,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125617,'Feco Gear','Extra Large Camera Backpack','Extra large camera backpack that is large enough to fit two pro-sized mirrorless cameras, with the ability to fit 5 lenses.',129.99,159.99,2,2.5,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125618,'UnderWearor','Small Camera Backpack','This small backpack will carry one camera and also one spare battery. It is lightweight to be taken on long hikes etc.',99.99,119.99,5,3.6,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125619,'Feco Gear','Camera Backpack','Adjustable dividers to fit your needs. Multiple compartments to keep all of your things organized.',149.99,169.99,1,4.7,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125620,'Trash Cannon','IXY D5 Waterproof','This new camera will allow you to take shots in the rain or in the swimming pool. No camera will ever get better than this.',599.99,799.99,2,3.9,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125621,'Trash Cannon','XL1 Camera','The technology that was used to develop this camera was so advanced for its time. That NASA took this camera onto the space shuttle.',899.99,1299.99,1,4.5,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125622,'Sony','Camera roll tape','The error rate on our new camera roll tape is beyond anything that our competitors have put to market in the last 3 years. Once you buy this you will never need to buy another roll of tape again.',49.99,49.99,7,3.1,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125623,'Sony','SD Card','Our 300MB storage card will allow you to take 2x as many photos. The speed to transfer your photos will be lighting fast. Also with incrediable backups.',39.99,59.99,24,2.9,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125624,'Nixon','Super zoom lens','This beautiful lens will allow your camera to zoom in 4x with 30% more pixles than ever before. You will be able to take a picture of a grain of sand.',199.99,299.99,64,5,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125625,'Nixon','Macro zoom lens','Placeholder Description',149.99,149.99,18,4.1,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125626,'Filmtown','Professional camera slider','Placeholder Description',69.99,79.99,31,3.1,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125627,'Filmtown','Professional camera tripod with slider','Placeholder Description',89.99,99.99,98,2.6,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125628,'Waka','Camera Sling Strap','Placeholder Description',69.99,79.99,225,1.8,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125629,'Waka','Premiuem Camera Sling','Placeholder Description',79.99,89.99,149,2.7,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125630,'DJU','3 Axis stablizer','Placeholder Description',419.99,459.99,49,0.6,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125631,'DJU','iPhone Stablizer','Placeholder Description',199.99,199.99,2,4.9,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125632,'Feco Gear','Lens filter','Placeholder Description',19.99,29.99,59,2.4,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125633,'Feco Gear','Lens polarizer','Placeholder Description',29.99,29.99,37,1.8,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125634,'DJU','4K Drone','Placeholder Description',899.99,999.99,16,2.9,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (125635,'StopPro','Hero 17 Black Edition','Placeholder Description',499.99,599.99,42,3.4,'photography hardware');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134510,'IBFailin','IBM PCjr','Talk about your bastard offspring. IBM''s attempt to build an inexpensive computer for homes and schools was an orphan almost from the start. The infamous "Chiclet" keyboard is virtually unusable for typing, and the computer can''t run much of the software written for its hugely successful parent, the IBM PC.',1499.99,299.99,8,4.5,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134511,'Microsoftish','Microsoft Windows Millennium (2000)','This might be the worst version of Windows ever released--or, at least, since the dark days of Windows 2.0. Windows Millennium Edition (aka Me, or the Mistake Edition), users report problems installing it, getting it to run, getting it to work with other hardware or software, and getting it to stop running.',1999.99,59.99,7,3,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134512,'Microsoftish','Microsoft Bob','a living room filled with clickable objects, and a series of cartoon "helpers" like Chaos the Cat and Scuzz the Rat that walked you through a small suite of applications. Fortunately, Bob was soon buried in the avalanche of hype surrounding Windows 95, though some of the cartoons lived on to annoy users of Microsoft Office and Windows XP (Clippy the animated paper clip, anyone?).',1499.99,79.99,12,4.6,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134513,'Microsoftish','Microsoft Internet Explorer 6 (2001)','Full of features, easy to use, and a virtual engraved invitation to hackers and other digital delinquents, Internet Explorer 6.x might be the least secure software on the planet.',2999.99,99.99,10,3,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134514,'Gatewaytofail','Gateway 2000 10th Anniversary PC (1995)','instead of Cristal champagne, buyers got Boone''s Farm--the so-called 6X CD-ROM spun at 4X or slower (a big performance hit in 1995), the video card was a crippled version of what people thought they were getting, and the surround-sound speakers weren''t actually surround-capable. Perhaps Gateway was sticking to the traditional gift for a tenth anniversary: It''s tin, not gold.',169.99,150.00,1,4.8,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134515,'IomegaBETA','Iomega Zip Drive','Click-click-click. That was the sound of data dying on thousands of Iomega Zip drives. Though Iomega sold tens of millions of Zip and Jaz drives that worked flawlessly, thousands of the drives died mysteriously, issuing a clicking noise as the drive head became misaligned and clipped the edge of the removable media, rendering any data on that disc permanently inaccessible.',79.99,499.99,8,2.1,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134516,'Comet System','Comet Systems Comet Cursor (1997)','Thank Comet Cursor for introducing spyware to an ungrateful nation. This simple program had one purpose: to change your mouse cursor into Bart Simpson, Dilbert, or one of thousands of other cutesy icons while you were visiting certain Web sites. But Comet had other habits that were not so cute.',39.99,159.99,22,2.5,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134517,'Appleish','Apple Macintosh Portable','Some buildings are portable, if you have access to a Freightliner. Stonehenge is a portable sun dial, if you have enough people on hand to get things rolling.',1049.99,119.99,3,3.6,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134518,'IBFailin','IBM Deskstar 75GXP','Fast, big, and highly unreliable, this 75GB hard drive was quickly dubbed the "Deathstar" for its habit of suddenly failing and taking all of your data with it.',999.99,169.99,19,4.7,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134519,'OQO','OQO Model 1','The 14-ounce OQO Model 1 billed itself as the "world''s smallest Windows XP computer"--and that was a big part of its problem.',1499.99,799.99,6,3.9,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134520,'digital conver.','DigitalConvergence CueCat','The company behind the device, DigitalConvergence, mailed hundreds of thousands of these cat-shaped bar-code scanners to subscribers of magazines and newspapers.',899.99,1299.99,5,4.5,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134521,'Eyetop','Eyetop Wearable DVD Player','Some things just aren''t meant to be done while walking or driving, and one of them is watching DVDs. Unfortunately, that message was lost on Eyetop.net, makers of the Eyetop Wearable DVD Player.',35999.99,49.99,45,3.1,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134522,'Appleish','The NoPhone Air','Cure your smartphone addiction by upgrading your expensive phone to the NoPhone Air. This cost-efficient model comes with an impressive 0 GB storage capacity and an impossibly thin, lightweight design that makes it feel as though you’re not even holding a phone!',799.99,59.99,1,2.9,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134523,'commodore','Commodore Plus/4','Commodore released like 2,000 computers in about 5 years time. That''s baffling. The Plus/4 was a home computer with a built-in software suite-word processor, spreadsheet, database, and graphs. It had 64kb of memory, a MOS 8501 proc, and a pretty snazzy-looking chassis. Unfortunately, Commodore 64 fans called it the Minus 60. ‘Nuff said.',789.98,299.99,8,5,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134524,'Sinclairish','Sinclair QL','The QL in the name was short for quantum leap, and with a Motorola 68008, 128KB of memory (expandable to 640KB), LAN ports, two built-in ZX Microdrive tape cartridges, and a built-in multi-tasking OS named QDOS, it certainly seemed advance.',389.99,149.99,16,4.1,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134525,'Hb','Refurbished Compaq Desktop','Refurbished HP Compaq Desktop: You Wont Complete any of your computing tasks with this refurbished HP Compaq Pro small form-factor desktop.',1044.99,79.99,3,3.1,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134526,'Dull','Refurbished OptiPlex Desktop','Refurbished..whatever that means. screen dont work but it works great as a paper weight',249.99,99.99,5,2.6,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134527,'Acar','Chrumybook - Sparkly Silver','get the best of the worst with this snail slow chrumybook laptop.',134.99,79.99,89,1.8,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134528,'Samsing','Samsing laptop','If it were any slower it would be called team targariate',159.99,89.99,6,2.7,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134529,'Dull','Dull laptop','i1 processor with almost no RAM, only thing more useless is the Team recreating Target in a game of thrones theme layout.',1129.99,459.99,18,0.6,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134530,'Applish','Mucbook novice','overpriced piece of hardware with legacy OS and tons of ram and no graphics card whatsoever.',912.99,199.99,56,4.9,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134531,'Dull','humanware laptop','Its like an alienware. nuff said, the bugs really are out of this world.',89.99,29.99,5,2.4,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134532,'Dull','laptop','busted screen, blue screen of death and overheating issues make this a one of a kind collectors item',999.99,29.99,8,1.8,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134533,'samsing','samsing ultimate laptop','no power source included, i5 processor with no RAM. spyware is included.',1199.99,999.99,14,2.9,'computer');
INSERT INTO products(sku,brand,product_title,product_desc,sale_price,msrp,quantity,star_rating,catagory) VALUES (134534,'Tushiba','Tushiba laptop','runs like a model T in modern times after being dissaembled, re assibled using plastic and then subjected to enough heat to fry the destroy an industrial grade manufacturing machine',799.99,599.99,18,3.4,'computer');



INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'hoitytoitywagon','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra.',2,'FALSE','Strap in for this one.....','TRUE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'ladidamusic','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',2,'FALSE','Not at all impressed.','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'mooseclone','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2,'FALSE','*insert clickbait title here*','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'fatuousapril','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',2,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'furbelowboil','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',2,'FALSE','Welp, that was disappointing...','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'trumpmocha','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Look, give it a chance!','TRUE','Mar, 26th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'pratfallbrick','blandit massa enim nec dui nunc',4,'FALSE','The bees knees MAN!!','TRUE','Sep, 23rd, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510121,'irkednag','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',4,'FALSE','This is the best I could give it.','TRUE','Oct, 11th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'ecdysiastequal','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',4,'FALSE','AAA product!','TRUE','Dec, 7th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'finagledodge','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',4,'FALSE','The last one was way better, but not bad.','TRUE','Jun, 24th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'bobbinbarge','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4,'FALSE','Don''t listen to these dummies!','TRUE','Aug, 8th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'nigglerebel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',4,'FALSE','Excellent content!','TRUE','Feb, 6th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'crudivorereset','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',4,'FALSE','It will do the job for now.','TRUE','Mar, 14th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'dudgeonarson','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Exciting, but not perfect...','TRUE','Aug, 27th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'quaggacold','blandit massa enim nec dui nunc',4,'TRUE','I have seen better','TRUE','Oct, 17th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (510130,'goombahtidal','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'TRUE','Expectations not met','TRUE','Jan, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'gewgawspout','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',1,'TRUE','This is dumb!','TRUE','Feb, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'egadtrio','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non. ',1,'TRUE','DO NOT BUY PRODUCT!!!11','TRUE','May, 9th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'folderoluncut','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'TRUE','Literally the WORST','TRUE','Jul, 5th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'klutzswept','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',1,'TRUE','Guess they call it WORST buy for a reason!','TRUE','Dec, 6th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'sousaphoneveto','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Broke almost immediately','TRUE','Feb, 14th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'panjandrumcolt','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',1,'FALSE','What even is this thing??','TRUE','Feb, 24th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'strudelangel','blandit massa enim nec dui nunc',1,'FALSE','READ BEFORE BUYING!!!','TRUE','Mar, 15th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125613,'hoipolloiglove','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'FALSE','exquisitely terrible','TRUE','Sep, 3rd, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'bladdergolf','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',5,'FALSE','Works as intended','FALSE','Nov, 9th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'briefsgiven','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',2,'FALSE','Strap in for this one.....','TRUE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'rearferry','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',3,'FALSE','Not at all impressed.','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'pilcrowfeast','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',4,'FALSE','*insert clickbait title here*','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'poppysmictrade','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'philtrumsaid','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',3,'FALSE','Welp, that was disappointing...','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'turduckenpug','blandit massa enim nec dui nunc',2,'FALSE','Look, give it a chance!','TRUE','Mar, 26th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (125610,'frumpydaily','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',4,'FALSE','The bees knees MAN!!','TRUE','Sep, 23rd, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'euphoniumherbs','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',1,'FALSE','This is the best I could give it.','TRUE','Oct, 11th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'centipedecomma','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',2,'FALSE','AAA product!','TRUE','Dec, 7th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'logorrhealair','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'FALSE','The last one was way better, but not bad.','TRUE','Jun, 24th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'quibblegem','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',1,'FALSE','Don''t listen to these dummies!','TRUE','Aug, 8th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'drizzlearise','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Excellent content!','TRUE','Feb, 6th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'rigmarolebats','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',1,'FALSE','It will do the job for now.','TRUE','Mar, 14th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'squabblespoof','blandit massa enim nec dui nunc',1,'FALSE','Exciting, but not perfect...','TRUE','Aug, 27th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134511,'flumesugar','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'TRUE','I have seen better','TRUE','Oct, 17th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'borborygmbrim','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',2,'TRUE','Expectations not met','TRUE','Jan, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'gogglessway','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non. ',3,'TRUE','This is dumb!','TRUE','Feb, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'wobbledig','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4,'TRUE','DO NOT BUY PRODUCT!!!11','TRUE','May, 9th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'poppycockshout','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',4,'TRUE','Literally the WORST','TRUE','Jul, 5th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'bodaciousmove','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',5,'TRUE','Guess they call it WORST buy for a reason!','TRUE','Dec, 6th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'wharfgreet','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Broke almost immediately','TRUE','Feb, 14th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'sagsquad','blandit massa enim nec dui nunc',4,'FALSE','What even is this thing??','TRUE','Feb, 24th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134515,'sandalspod','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',3,'FALSE','READ BEFORE BUYING!!!','TRUE','Mar, 15th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'hunkyemail','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',2,'FALSE','exquisitely terrible','TRUE','Sep, 3rd, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'cockalorumfront','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',1,'FALSE','Works as intended','FALSE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'shabbygarlic','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'FALSE','Strap in for this one.....','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'satisfyingpistachio','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',2,'FALSE','Not at all impressed.','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'maternallard','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',3,'FALSE','*insert clickbait title here*','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'temptingmilkshakes','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'guardedchile','blandit massa enim nec dui nunc',1,'FALSE','Welp, that was disappointing...','TRUE','Mar, 26th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235608,'handsomebasmati','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',3,'FALSE','Look, give it a chance!','TRUE','Sep, 23rd, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'pristineabalone','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',2,'FALSE','The bees knees MAN!!','TRUE','Oct, 11th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'variousoil','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',4,'FALSE','This is the best I could give it.','TRUE','Dec, 7th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'importedicecream','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'FALSE','AAA product!','TRUE','Jun, 24th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'boldapricots','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',2,'FALSE','The last one was way better, but not bad.','TRUE','Aug, 8th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'acridsardines','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Don''t listen to these dummies!','TRUE','Feb, 6th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'unwittingcoconut','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',1,'FALSE','Excellent content!','TRUE','Mar, 14th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'grizzledoatmeal','blandit massa enim nec dui nunc',1,'FALSE','It will do the job for now.','TRUE','Aug, 27th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235616,'sweetquiche','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'FALSE','Exciting, but not perfect...','TRUE','Oct, 17th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'nostalgicchowder','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',1,'TRUE','I have seen better','TRUE','Jan, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'digitalmuesli','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',1,'TRUE','Expectations not met','TRUE','Feb, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'pastelapples','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2,'TRUE','This is dumb!','TRUE','May, 9th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'drabcrackers','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',3,'TRUE','DO NOT BUY PRODUCT!!!11','TRUE','Jul, 5th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'cuddlysyrup','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',4,'TRUE','Literally the WORST','TRUE','Dec, 6th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'beautifulrelish','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'TRUE','Guess they call it WORST buy for a reason!','TRUE','Feb, 14th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'imperfectmayonnaise','blandit massa enim nec dui nunc',5,'FALSE','Broke almost immediately','TRUE','Feb, 24th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (134529,'wastefulcheese','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',4,'FALSE','What even is this thing??','TRUE','Mar, 15th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'alienatedpolenta','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra.',4,'FALSE','READ BEFORE BUYING!!!','TRUE','Sep, 3rd, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'capitalsausage','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',3,'FALSE','exquisitely terrible','TRUE','Nov, 9th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'worthwhiletacos','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2,'FALSE','Works as intended','FALSE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'sanecake','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',1,'FALSE','Strap in for this one.....','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'squeamishsalt','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',2,'FALSE','Not at all impressed.','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'futurepepper','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',3,'FALSE','*insert clickbait title here*','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'racialtruffle','blandit massa enim nec dui nunc',4,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,recommended,review_title,verified,date) VALUES (235620,'acousticlollies','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'FALSE','Welp, that was disappointing...','TRUE','Mar, 26th, 2016');
