DROP DATABASE IF EXISTS worstBuyReviews;

CREATE DATABASE worstBuyReviews;

USE worstBuyReviews;

CREATE TABLE products (
  id int AUTO_INCREMENT PRIMARY KEY,
  sku int NOT NULL,
  brand VARCHAR(255),
  product_title VARCHAR(255),
  product_desc VARCHAR(255),
  sale_price DECIMAL(10, 2) NOT NULL,
  msrp DECIMAL(10, 2) NOT NULL,
  quantity int NOT NULL,
  star_rating int,
  catagory VARCHAR(255) NOT NULL
);

CREATE TABLE reviews (
  id int AUTO_INCREMENT PRIMARY KEY,
  product_sku int NOT NULL,
  username VARCHAR(20),
  review_body VARCHAR(255),
  star_rating int,
  review_title VARCHAR(255),
  recommended VARCHAR(255),
  verified VARCHAR(255),
  date VARCHAR(255) NOT NULL
);

INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235601, 'Samsing', 'Industrial Size washing machine', 'A washing machine with the quality of a laundrimat machine, able to wash an entire sweat shops uniforms in one load', 1499.99, 1500.00, 8, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235602, 'LH', 'Bottom control dishwasher', 'A dishwasher where you would lay on the floor to operate controls. Allows easy loading of dishwasher', 1999.99, 699.99, 7, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235603, 'Whurlpool', 'Left of range microwave', 'A microwave that SPECIFICALLY gets placed to the LEFT of your range.', 1499.99, 799.99, 12, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235604, 'Maytog', 'No door refigerator', 'A easy to not access refigerator for those trying to lose weight', 2999.99, 3499.99, 10, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235605, 'KitchenHinder', 'Low performance blender', 'A blender that may be worse than just dicing with a knife', 169.99, 199.99, 1, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235606, 'Dieson', 'Super sonic hair wetter', 'Makes wetting your hair outside of the shower quick and easy with no hoses attached!', 79.99, 119.99, 8, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235607, 'Keurigged', 'K classic', 'Our classic K coffee maker will sometimes brew your coffee when asked. Good luck setting it up', 39.99, 49.99, 22, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235608, 'jRobot', 'Claymore Roomba', 'The classic take on the Roomba, but with a claymore anit-personel mine strapped to the top. Will trigger when anything gets in the way, use with care!', 1049.99, 1299.99, 3, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235609, 'Posche', 'Convertible range hood', 'Actually blows air onto your range top.', 999.99, 1499.99, 19, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235610, 'Volcanicair', 'Non-stainless steel refrigerator', 'Nice finish refigerator that will last you about a week in humid climates. (finish may rust over time)', 1499.99, 1799.99, 6, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235611, 'BE appliances', 'Free standing electric range', "The perfect addition to your kitchen if you aren't good at cooking so you can blame it on the fact that it's electric and doesn't heat correctly.", 899.99, 999.99, 5, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235612, 'Atlantic kitchen', 'Dracor refigerator', 'You want to flex in all of your friends and family? Pick up this sweet refigerator that has hologram numbers to tell you the exact temperature.', 35999.99, 19999.99, 45, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235613, 'Samsing', 'Family Hub 94 cu. in. refrigerator', 'For those families that LOVE to eat and love to spend 800 bucks a week on groceries then eat out anyway.', 799.99, 999.99, 1, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235614, 'Samsing', 'Under the range mirowave', 'This mircowave conveniently sits underneath your range so you can cook while you cook dawg.', 78.99, 84.99, 8, 5, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235615, 'Samsing', 'POWERbot robot vacuum cleaner', "This robot vacuum cleaner is way less cool than the claymore Roomba, but probably won't blow up upon contact with walls.", 389.99, 399.99, 16, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235616, 'Samsing', 'High Tech dryer', 'The highest of high tech clothes dryer for any amount of clothes you could possibly load.', 44.99, 68.99, 3, 3, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235617, 'Dieson', 'Ball Animal vacuum cleaner', 'Picks all those pesky animals right off of the floor of your home, works up to 25lb body weight animals', 249.99, 299.99, 5, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235618, 'Dieson', 'Max cool fan', "Kind of just blows stale air for those of you that don't have central air in the year 2020", 34.99, 49.99, 89, 1, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235619, 'Dieson', 'V7 cordless hand vac', 'Cordless hand held vacuum that has about 2 minutes of run time with a 4 hour recharge!', 159.99, 189.99, 6, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235620, 'Keurigged', 'Latte maker', 'Makes a mediocre latte with mostly milk and room temperature, perfect for those that are not really big into coffee, but huge into milk!', 129.99, 189.99, 18, 1, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235621, 'Keurigged', 'Single serve and carafe coffee maker', 'Makes about a third of a cup of coffee per K cup! ', 12.99, 19.99, 56, 4, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235622, 'Keurigged', 'K-Elite coffee maker', 'Makes about a half a cup of coffee and looks pretty cool! Guaranteed at least one usage', 89.99, 99.99, 5, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235623, 'Volcanicair', "Short tub built in dishwasher", "Fits about one plate in there! Who doesn't want to wash one dish at a time?", 999.99, 1199.99, 8, 1, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235624, 'Volcanicair', 'Gas cook-top', 'Gas cooktop that uses portable propane tanks to fuel it. Has about 15 seconds of runtime per propane tank!', 1199.99, 1499.99, 14, 2, 'Appliances');
INSERT INTO products (sku, brand, product_title, product_desc, sale_price, msrp, quantity, star_rating, catagory) VALUES (235625, 'Volcanicair', 'Self-dirtying oven', 'Everything you could ever want in an oven. Seems to make itself dirty even without use somehow.', 799.99, 1199.99, 18, 3, 'Appliances');


INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'hoitytoitywagon','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra.',2,'FALSE','Strap in for this one.....','TRUE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'ladidamusic','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',2,'FALSE','Not at all impressed.','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'mooseclone','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2,'FALSE','*insert clickbait title here*','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'fatuousapril','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',2,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'furbelowboil','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',2,'FALSE','Welp, that was disappointing...','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'trumpmocha','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Look, give it a chance!','TRUE','Mar, 26th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'pratfallbrick','blandit massa enim nec dui nunc',4,'FALSE','The bees knees MAN!!','TRUE','Sep, 23rd, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510121,'irkednag','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',4,'FALSE','This is the best I could give it.','TRUE','Oct, 11th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'ecdysiastequal','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',4,'FALSE','AAA product!','TRUE','Dec, 7th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'finagledodge','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',4,'FALSE','The last one was way better, but not bad.','TRUE','Jun, 24th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'bobbinbarge','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4,'FALSE','Don''t listen to these dummies!','TRUE','Aug, 8th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'nigglerebel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',4,'FALSE','Excellent content!','TRUE','Feb, 6th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'crudivorereset','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',4,'FALSE','It will do the job for now.','TRUE','Mar, 14th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'dudgeonarson','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Exciting, but not perfect...','TRUE','Aug, 27th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'quaggacold','blandit massa enim nec dui nunc',4,'TRUE','I have seen better','TRUE','Oct, 17th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (510130,'goombahtidal','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'TRUE','Expectations not met','TRUE','Jan, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'gewgawspout','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',1,'TRUE','This is dumb!','TRUE','Feb, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'egadtrio','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non. ',1,'TRUE','DO NOT BUY PRODUCT!!!11','TRUE','May, 9th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'folderoluncut','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'TRUE','Literally the WORST','TRUE','Jul, 5th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'klutzswept','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',1,'TRUE','Guess they call it WORST buy for a reason!','TRUE','Dec, 6th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'sousaphoneveto','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Broke almost immediately','TRUE','Feb, 14th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'panjandrumcolt','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',1,'FALSE','What even is this thing??','TRUE','Feb, 24th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'strudelangel','blandit massa enim nec dui nunc',1,'FALSE','READ BEFORE BUYING!!!','TRUE','Mar, 15th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125613,'hoipolloiglove','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'FALSE','exquisitely terrible','TRUE','Sep, 3rd, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'bladdergolf','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',5,'FALSE','Works as intended','FALSE','Nov, 9th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'briefsgiven','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',2,'FALSE','Strap in for this one.....','TRUE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'rearferry','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',3,'FALSE','Not at all impressed.','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'pilcrowfeast','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',4,'FALSE','*insert clickbait title here*','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'poppysmictrade','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'philtrumsaid','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',3,'FALSE','Welp, that was disappointing...','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'turduckenpug','blandit massa enim nec dui nunc',2,'FALSE','Look, give it a chance!','TRUE','Mar, 26th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (125610,'frumpydaily','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',4,'FALSE','The bees knees MAN!!','TRUE','Sep, 23rd, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'euphoniumherbs','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',1,'FALSE','This is the best I could give it.','TRUE','Oct, 11th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'centipedecomma','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',2,'FALSE','AAA product!','TRUE','Dec, 7th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'logorrhealair','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'FALSE','The last one was way better, but not bad.','TRUE','Jun, 24th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'quibblegem','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',1,'FALSE','Don''t listen to these dummies!','TRUE','Aug, 8th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'drizzlearise','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Excellent content!','TRUE','Feb, 6th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'rigmarolebats','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',1,'FALSE','It will do the job for now.','TRUE','Mar, 14th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'squabblespoof','blandit massa enim nec dui nunc',1,'FALSE','Exciting, but not perfect...','TRUE','Aug, 27th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134511,'flumesugar','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'TRUE','I have seen better','TRUE','Oct, 17th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'borborygmbrim','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',2,'TRUE','Expectations not met','TRUE','Jan, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'gogglessway','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non. ',3,'TRUE','This is dumb!','TRUE','Feb, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'wobbledig','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4,'TRUE','DO NOT BUY PRODUCT!!!11','TRUE','May, 9th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'poppycockshout','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',4,'TRUE','Literally the WORST','TRUE','Jul, 5th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'bodaciousmove','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',5,'TRUE','Guess they call it WORST buy for a reason!','TRUE','Dec, 6th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'wharfgreet','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Broke almost immediately','TRUE','Feb, 14th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'sagsquad','blandit massa enim nec dui nunc',4,'FALSE','What even is this thing??','TRUE','Feb, 24th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134515,'sandalspod','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',3,'FALSE','READ BEFORE BUYING!!!','TRUE','Mar, 15th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'hunkyemail','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',2,'FALSE','exquisitely terrible','TRUE','Sep, 3rd, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'cockalorumfront','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',1,'FALSE','Works as intended','FALSE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'shabbygarlic','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'FALSE','Strap in for this one.....','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'satisfyingpistachio','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',2,'FALSE','Not at all impressed.','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'maternallard','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',3,'FALSE','*insert clickbait title here*','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'temptingmilkshakes','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'guardedchile','blandit massa enim nec dui nunc',1,'FALSE','Welp, that was disappointing...','TRUE','Mar, 26th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235608,'handsomebasmati','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',3,'FALSE','Look, give it a chance!','TRUE','Sep, 23rd, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'pristineabalone','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',2,'FALSE','The bees knees MAN!!','TRUE','Oct, 11th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'variousoil','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',4,'FALSE','This is the best I could give it.','TRUE','Dec, 7th, 2016');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'importedicecream','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1,'FALSE','AAA product!','TRUE','Jun, 24th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'boldapricots','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',2,'FALSE','The last one was way better, but not bad.','TRUE','Aug, 8th, 2017');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'acridsardines','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',1,'FALSE','Don''t listen to these dummies!','TRUE','Feb, 6th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'unwittingcoconut','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',1,'FALSE','Excellent content!','TRUE','Mar, 14th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'grizzledoatmeal','blandit massa enim nec dui nunc',1,'FALSE','It will do the job for now.','TRUE','Aug, 27th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235616,'sweetquiche','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'FALSE','Exciting, but not perfect...','TRUE','Oct, 17th, 2018');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'nostalgicchowder','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Hendrerit gravida rutrum quisque non tellus orci.',1,'TRUE','I have seen better','TRUE','Jan, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'digitalmuesli','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',1,'TRUE','Expectations not met','TRUE','Feb, 14th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'pastelapples','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2,'TRUE','This is dumb!','TRUE','May, 9th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'drabcrackers','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',3,'TRUE','DO NOT BUY PRODUCT!!!11','TRUE','Jul, 5th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'cuddlysyrup','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',4,'TRUE','Literally the WORST','TRUE','Dec, 6th, 2019');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'beautifulrelish','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',4,'TRUE','Guess they call it WORST buy for a reason!','TRUE','Feb, 14th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'imperfectmayonnaise','blandit massa enim nec dui nunc',5,'FALSE','Broke almost immediately','TRUE','Feb, 24th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (134529,'wastefulcheese','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',4,'FALSE','What even is this thing??','TRUE','Mar, 15th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'alienatedpolenta','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra.',4,'FALSE','READ BEFORE BUYING!!!','TRUE','Sep, 3rd, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'capitalsausage','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa. Consectetur libero id faucibus nisl tincidunt eget nullam non.',3,'FALSE','exquisitely terrible','TRUE','Nov, 9th, 2020');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'worthwhiletacos','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2,'FALSE','Works as intended','FALSE','Jun, 2nd, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'sanecake','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in nisl. Ultrices sagittis orci a scelerisque purus semper eget duis at.',1,'FALSE','Strap in for this one.....','TRUE','Nov, 12th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'squeamishsalt','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Tortor dignissim convallis aenean et tortor.',2,'FALSE','Not at all impressed.','TRUE','Nov, 30th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'futurepepper','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit.',3,'FALSE','*insert clickbait title here*','TRUE','Dec, 6th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'racialtruffle','blandit massa enim nec dui nunc',4,'FALSE','Bro, REALLY?!!!','TRUE','Dec, 9th, 2015');
INSERT INTO reviews(product_sku,username,review_body,star_rating,review_title,recommended,verified,date) VALUES (235620,'acousticlollies','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet dictum sit amet justo donec enim diam vulputate. Volutpat commodo sed egestas egestas fringilla phasellus.',1,'FALSE','Welp, that was disappointing...','TRUE','Mar, 26th, 2016');
